### ISSUE TITLE
Mails Populating db but not the inbox view

### ISSUE THREAD

**Issue by ritvick** [ruffrey/mailsac#11]
Hey,

I am sending mails from gmail to my custom domain, the script is also hosted on my server. 
Now I can see the mongo db populating, but the mails do not show up when I open page. Page title count is correct, but the body does not have mails. When I click on JSON / RSS links, I can see the content, but not in html. 

http://domainname.com:3000/inbox/test@domainname.com

"domainname.com" is not real domain, just for reference.

Even on gmail I receive failure daemon mails. Why this is the case , when we caught mails and fed them to mongodb.

**Comment by ritvick** [comment]
Partial Fix from pull/#12

**Comment by adamlazz** [comment]
I am also seeing this issue, thank you for submitting.

Issue #13 may explain the failure daemon mails.

**Comment by lifehome** [comment]
I think this is something to do with simplesmtp due to its "deprecated" status?
