### ISSUE TITLE
Installing MailSac on my own server - complete steps

### ISSUE THREAD

**Issue by rahulmr** [ruffrey/mailsac#16]
Sorry to trouble again, but I see no documentation on how to install mailsac on my own server (say Ubuntu 14.04 VPS) and set domain of my own with reverse DNS and other settings.  

I was able to install and get the url on http://mail.mydomain.ga but then the UI shows ---@mailsac.com instead of something like ---@mail.mydomain.ga or ---@mydomain.ga  

I wanted to configure http://mail.mydomain.ga as the website address and mails like ----@mail.mydomain.ga and/or ----@mydomain.ga.   

Also, while installing I had to install mongodb and create db like mailsac and add user to it. Then add those users in the config.js file.   

Any help on this topic could be very helpful.   
Thanks in advance!

**Comment by ruffrey** [comment]
Hi, there is no UI option to change the name in this version afaik. In the next week or so I expect to have a new version out which will be easier to install. It has been hard to make the time to work on this.

**Comment by ruffrey** [comment]
Latest version, see `./install/` folder.
