### ISSUE TITLE
How can i add the requester IP address to logs? 

### ISSUE THREAD

**Issue by fmrosa** [ruffrey/mailsac#19]
There is a way to log the requester IP address to mailsac.log?

**Comment by ruffrey** [comment]
During an HTTP request to the UI, or during SMTP stuff?

**Comment by fmrosa** [comment]
The HTTP request. I just wanted to keep IP logs of people who accessed the UI for auditing in case something goes wrong or bad.

**Comment by ruffrey** [comment]
It is a standard express app using morgan for logging.

The middleware in mailsac is here:
https://github.com/ruffrey/mailsac/blob/master/app.js#L112

morgan logger formatting docs:
https://github.com/expressjs/morgan#predefined-formats
