### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by cwBrendan** [ruffrey/mailsac#21]
I have mailsac setup and our IT department believes they have everything configured correctly on their end. When I attempt to send an email to the server I receive the following fail reply message:

The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720
[199.246.133.60 199.246.133.60: socket error]

(We use corporate gmail hence the Google link in the email). So I'm wondering how I can find out more information about the socket error and what the possible culprits might be. Looking at the documentation it appears that mailsac has a debug mode but I'm not clear on how to enable it. Any help is appreciated.

**Comment by ruffrey** [comment]
You would need to look at the log output from mailsac. `/var/log/mailsac.log` on ubuntu, if you use the setup scripts.

**Comment by ruffrey** [comment]
It sounds like the mailsac server was behind a firewall or something and google mail couldn't get there.

Closing for now, but feel free to reopen with more details.
