### ISSUE TITLE
Deployed to domain but not receiving the emails.

### ISSUE THREAD

**Issue by RSPaul** [ruffrey/mailsac#24]
I have followed the exact instructions mentioned here: https://github.com/ruffrey/mailsac/blob/master/README.md

My server is ubuntu 14.04 and installed:
Node.js = 0.12.15
mongoDB
redis
Nothing blocking the mail ports (25 and 587)
But it is not receiving any emails i am sending to any of the accounts. But it did receives the email here:
https://mailsac.com/

Please let me know if there is any other extra configuration required  to make it working.

Thanks

**Comment by heathermhuang** [comment]
You need to change @mailsac.com to your domain name and point your domain's MX record to the IP address.

**Comment by ruffrey** [comment]
@RSPaul I think @heathermhuang is onto something here. It sounds like you just did this: https://mailsac.com/docs/free-email-for-your-domain-setup which will send email to mailsac.com. You'd need it to set the MX records with your DNS provider to the domain and/or ip address of your server.

Closing for now, but feel free to reopen with more details.
