### ISSUE TITLE
link inactive

### ISSUE THREAD

**Issue by screamolic** [ruffrey/mailsac#27]
im open my email , i click unblock, but it still blocked.

**Comment by ruffrey** [comment]
Hello - can you be a little more specific about the context? Is this on the website (mailsac.com) or are you running it yourself? Unblocking opens in a new window - is it possible the browser is blocking that?

**Comment by screamolic** [comment]
yes, im using mailsac . i dont know sure if my firefox blocking it.

**Comment by ruffrey** [comment]
Mailsac.com or self hosted?

**Comment by screamolic** [comment]
mailsac sir.
im user another OS and the result is same like my PC. inactive link.

**Comment by screamolic** [comment]
hellooo...

**Comment by ruffrey** [comment]
Clicking "Unblock links and images" will open a new tab; it does not unblock them within the page. My best guess is that your browser is keeping it from opening a new tab.

**Comment by screamolic** [comment]
no, i have trying in different browser and OS.

**Comment by ruffrey** [comment]
With the information you have provided, I am unable to reproduce this problem you are describing. If there was more information, I might be able to do something to help. It sounds like a new browser tab is not opening with the unblocked message. I tried all the latest desktop browsers, and mobile Safari (maybe you have older versions? which OS versions exactly?). Without screenshots/screencasts, specific information, or developer tools output, there just isn't anything else I can do. Nobody else has reported it, either, but hopefully if it happens to someone else they can provide more information. Sorry about that.
