### ISSUE TITLE
mailsac.com not working

### ISSUE THREAD

**Issue by kadirgun** [ruffrey/mailsac#30]
Hello mailsac.com not working now.

**Comment by k0nsl** [comment]
Yes, confirmed. It isn't working for me, either.

**Comment by ruffrey** [comment]
Things are working again.

There should have been alerts going off as a particular server was running out of disk space. That alert was silenced by mistake a couple months ago, and forgotten. Then a new log rotation script  had an error, and log files ballooned to consume all disk.
