### ISSUE TITLE
Setup Configuration Help

### ISSUE THREAD

**Issue by pinotnoir** [ruffrey/mailsac#4]
I'm trying to set up a mailsac test app on my local winginx server, but don't have any node.js experience yet and thus it doesn't run. All I see is "Node.js basic web application" when navigating to my mailsec.dev url. 

When you mention to "just update the config.js", is this really all there is to it? Could you possibly post your example config file or provide a small tutorial to get me started on it. 

My nodjs.conf currently points to: server = home/mailsac.dev\servermailsac.js. Is this correct?

Many thanks.

**Comment by ritvick** [comment]
I ran both the scripts. I have created a new domain and created mx entries to my ip where I have the script running. How does the script will catch the emails, does it have a incoming mail server implemented to catch email.

I am bit confused with smtp.js as well. Why that is needed when we are not sending email from the script.  We only need to catch emails.
