### ISSUE TITLE
How to change encoding to UTF-8? 

### ISSUE THREAD

**Issue by fabiomeneses** [ruffrey/mailsac#7]
Im translating mailsac to portuguese and im getting charset errors. How to fix encoding to UTF-8? 

Thanks.

**Comment by ruffrey** [comment]
Hey, awesome. Great question. What do the errors look like? Precisely when do they happen?

**Comment by fabiomeneses** [comment]
Hello. thanks for the answer. 

The page looks like this: 
Endere�os de E-mail tempor�rios instant�neos.
but the code look like this: 
Endereços de E-mail temporários instantâneos

I tried to add the line below to the HTML head, but didn't worked and i got the same errors. Apparently the node.js app is already using a different charset: 

This is what i tried: 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

How do i change the node.js charset? 

Thanks.

**Comment by fabiomeneses** [comment]
ops.. sorry. i closed the thread by mistake. Can you please advise?

**Comment by ruffrey** [comment]
Hey @fabiomeneses - can you add a screenshot maybe? Is it just the HTML page encoding vs the mailsac server?

**Comment by fabiomeneses** [comment]
Hello ruffrey. 

I made it! just replaced the accented words by the HTML entity listed on this document. 
http://www.javascripter.net/faq/accentedcharacters.htm

Thank you. You have a great product here...
