### ISSUE TITLE
Alternate e-mail address

### ISSUE THREAD

**Issue by fabiomeneses** [ruffrey/mailsac#8]
Hello, 

Do you have plans to release the alternate e-mail address feature for Mailsac on github? This feature is awesome on providing some sort of privacy for the inboxes. 

congrats on the project. 

Regards,

**Comment by ruffrey** [comment]
Hey,
Yes this new version on the website will be release, minus the paid
features. Just need to carve out some time to apply a few fixes and extract
the payment code. It's a semi-rewrite.
Jeff

On Wed, Mar 18, 2015 at 5:55 AM, fabiomeneses <notifications@github.com>
wrote:

> Hello,
>
> Do you have plans to release the alternate e-mail address feature for
> Mailsac on github? This feature is awesome on providing some sort of
> privacy for the inboxes.
>
> congrats on the project.
>
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruffrey/mailsac/issues/8>.
>



-- 
Phone: +1-916-801-6693
Skype: jeffhparrish
Hangouts: jeffhparrish@gmail.com

**Comment by fabiomeneses** [comment]
Awesome. Thanks for the prompt response.
